# Generated by Django 5.1.2 on 2024-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SorgulamaSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kimlik_seri', models.CharField(max_length=10)),
                ('kimlik_numarasi', models.CharField(max_length=20)),
                ('fin_kod', models.CharField(max_length=10)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('ata_adi', models.CharField(max_length=50)),
                ('dogum_tarixi', models.DateField()),
                ('cinsiyet', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('emlak_bilgisi', models.JSONField()),
                ('taxes_bilgisi', models.TextField()),
                ('infocenter_bilgisi', models.JSONField()),
                ('abonent_adi', models.CharField(max_length=100)),
                ('sorgulama_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
