# Generated by Django 5.1.2 on 2024-10-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='abonent_adi',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='emlak_bilgisi',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='infocenter_bilgisi',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='sorgulama_tarihi',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='taxes_bilgisi',
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='abonent_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='emlak_sonuc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='infocenter_sonuc',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='tax_sonuc',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='ad',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='ata_adi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='cinsiyet',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='dogum_tarixi',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='fin_kod',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='kimlik_numarasi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='kimlik_seri',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='soyad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
