# Generated by Django 5.1.2 on 2024-10-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sorgulamasonucu_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorgulamasonucu',
            options={'verbose_name': 'Axtarish sistemi', 'verbose_name_plural': 'Axtarish neticeleri'},
        ),
    ]
