# Generated by Django 5.1.2 on 2024-10-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_sorgulamasonucu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorgulamasonucu',
            options={},
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='aile_terkibi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='abonent_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='ad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='ata_adi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='emlak_sonuc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='infocenter_sonuc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='soyad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='tax_sonuc',
            field=models.TextField(null=True),
        ),
    ]
