# Generated by Django 5.1.2 on 2024-10-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_sorgulamasonucu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='abonent_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='emlak_sonuc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='infocenter_sonuc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sorgulamasonucu',
            name='tax_sonuc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
