# Generated by Django 5.1.2 on 2024-10-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_sorgulamasonucu_abonent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='mentqe_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='secici_unvani',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
