# Generated by Django 5.1.2 on 2024-10-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_sorgulamasonucu_daire_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='daire_id',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='mentqe_id',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='secici_unvani',
        ),
    ]
