# Generated by Django 5.1.2 on 2024-11-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_sorgulamasonucu_abonent_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sorgulamasonucu',
            old_name='emlak_sonuc',
            new_name='abonent_adlari',
        ),
        migrations.RenameField(
            model_name='sorgulamasonucu',
            old_name='infocenter_sonuc',
            new_name='cinayet_bilgisi',
        ),
        migrations.RenameField(
            model_name='sorgulamasonucu',
            old_name='tax_sonuc',
            new_name='emlak_bilgisi',
        ),
        migrations.RemoveField(
            model_name='sorgulamasonucu',
            name='abonent_name',
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='infocenter_bilgisi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='inzibati_bilgisi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='mehkeme_bilgisi',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sorgulamasonucu',
            name='vergi_bilgisi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
