# Generated by Django 5.1.2 on 2024-11-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_emlak_sonuc_sorgulamasonucu_abonent_adlari_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorgulamaSonuclari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('ata_adi', models.CharField(blank=True, max_length=100, null=True)),
                ('kimlik_seri', models.CharField(max_length=10)),
                ('kimlik_numarasi', models.CharField(max_length=20)),
                ('fin_kod', models.CharField(max_length=10)),
                ('dogum_tarixi', models.DateField()),
                ('cinsiyet', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('taxes_info', models.TextField(blank=True, null=True)),
                ('emlak_info', models.JSONField(blank=True, null=True)),
                ('infocenter_info', models.JSONField(blank=True, null=True)),
                ('aile_terkibi', models.JSONField(blank=True, null=True)),
                ('abonent_names', models.JSONField(blank=True, null=True)),
                ('mehkeme_result', models.JSONField(blank=True, null=True)),
                ('cinayet_result', models.JSONField(blank=True, null=True)),
                ('inzibati_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SorgulamaSonucu',
        ),
    ]
